env:
   global:
   - GCC_BASE=gcc-arm-none-eabi-10-2020-q4-major
   - GCC_SHORT=10-2020q4

sudo: required
language: generic
dist: xenial 

addons:
  apt:
    packages:
      libc6-i386
      cppcheck
      python3

cache:
  directories:
    - $HOME/$GCC_BASE

install:
    - export GCC_DIR=$HOME/$GCC_BASE
    - export GCC_ARCHIVE=$HOME/$GCC_BASE-linux.tar.bz2
    - export GCC_URL=https://developer.arm.com/-/media/Files/downloads/gnu-rm/$GCC_SHORT/$GCC_BASE-x86_64-linux.tar.bz2
    - if [ ! -e $GCC_DIR/bin/arm-none-eabi-g++ ]; then wget $GCC_URL -O $GCC_ARCHIVE; tar xfj $GCC_ARCHIVE -C $HOME; fi
    - ROOTLOC="../.."
    - BUILDLOC=mchf-eclipse/build
    - export MAKEFLAGS=-j2 
script:
    - cd ../..
    - make all-firmware
    - make all-bootloader
    - bash scripts/static_analysis.sh
    - bash scripts/size_regression.sh
    - bash scripts/analyze_wcet.sh
before_deploy:
    - sudo apt-get install -y doxygen graphviz
    - make docs > /dev/null && tar -czf docs.tar.gz -C .. docs
deploy:
  provider: releases
  api_key:
    secure: "6kEbfOiJSR7FgDmmLNVTEg"
  file: 
  - build/fw-f4/fw-mchf.bin
  - build/fw-f7/fw-ovi40.bin
  - build/fw-h7/fw-vi40h7.bin
  - build/bl-f4/bl-mchf.bin
  - build/bl-f7/bl-ovi40.bin
  - build/bl-h7/bl-i40h7.bin  
  - build/fw-f4/fw-mchf.dfu
  - build/fw-f7/fw-ovi40.dfu
  - build/fw-h7/fw-i40h7.dfu  
  - build/bl-f4/bl-mchf.dfu
  - build/bl-f7/bl-ovi40.dfu
  - build/bl-h7/bl-i40h7.dfu
  skip_cleanup: true
  on:
    repo: db4ple/UHSDR
    tags: true
    branches: 
      only:
      - active-devel 
