basesw/ovi40/Src/stm32f7xx_it.o: basesw/ovi40/Src/stm32f7xx_it.c \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal.h \
 basesw/ovi40/Inc/stm32f7xx_hal_conf.h basesw/ovi40/Inc/main.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_rcc.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_def.h \
 basesw/ovi40/Drivers/CMSIS/Device/ST/STM32F7xx/Include/stm32f7xx.h \
 basesw/ovi40/Drivers/CMSIS/Device/ST/STM32F7xx/Include/stm32f767xx.h \
 basesw/ovi40/Drivers/CMSIS/Include/core_cm7.h \
 basesw/ovi40/Drivers/CMSIS/Include/core_cmInstr.h \
 basesw/ovi40/Drivers/CMSIS/Include/cmsis_gcc.h \
 basesw/ovi40/Drivers/CMSIS/Include/core_cmFunc.h \
 basesw/ovi40/Drivers/CMSIS/Include/core_cmSimd.h \
 basesw/ovi40/Drivers/CMSIS/Device/ST/STM32F7xx/Include/system_stm32f7xx.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_rcc_ex.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_gpio.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_gpio_ex.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_dma.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_dma_ex.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_cortex.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_adc.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_adc_ex.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_dac.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_dac_ex.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_flash.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_flash_ex.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_sram.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_ll_fmc.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_i2c.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_i2c_ex.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_pwr.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_pwr_ex.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_rtc.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_rtc_ex.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_sai.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_spi.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_tim.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_tim_ex.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_pcd.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_ll_usb.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_pcd_ex.h \
 basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_hcd.h \
 basesw/ovi40/Inc/stm32f7xx_it.h hardware/uhsdr_board.h \
 hardware/uhsdr_board_config.h \
 hardware/board_configs/UHSDR_UI_mchf_config.h hardware/uhsdr_types.h \
 basesw/ovi40/Drivers/CMSIS/Include/arm_math.h \
 basesw/ovi40/Drivers/CMSIS/Include/core_cm7.h hardware/uhsdr_mcu.h \
 drivers/audio/audio_filter.h hardware/uhsdr_types.h \
 drivers/ui/oscillator/osc_interface.h drivers/ui/lcd/ui_lcd_layouts.h \
 drivers/ui/lcd/ui_lcd_hy28.h drivers/ui/ui_vkeybrd.h \
 drivers/audio/audio_driver.h hardware/uhsdr_board_config.h \
 drivers/audio/softdds/softdds.h drivers/audio/softdds/dds_table.h \
 drivers/audio/audio_filter.h
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal.h:
basesw/ovi40/Inc/stm32f7xx_hal_conf.h:
basesw/ovi40/Inc/main.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_rcc.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_def.h:
basesw/ovi40/Drivers/CMSIS/Device/ST/STM32F7xx/Include/stm32f7xx.h:
basesw/ovi40/Drivers/CMSIS/Device/ST/STM32F7xx/Include/stm32f767xx.h:
basesw/ovi40/Drivers/CMSIS/Include/core_cm7.h:
basesw/ovi40/Drivers/CMSIS/Include/core_cmInstr.h:
basesw/ovi40/Drivers/CMSIS/Include/cmsis_gcc.h:
basesw/ovi40/Drivers/CMSIS/Include/core_cmFunc.h:
basesw/ovi40/Drivers/CMSIS/Include/core_cmSimd.h:
basesw/ovi40/Drivers/CMSIS/Device/ST/STM32F7xx/Include/system_stm32f7xx.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_rcc_ex.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_gpio.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_gpio_ex.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_dma.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_dma_ex.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_cortex.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_adc.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_adc_ex.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_dac.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_dac_ex.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_flash.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_flash_ex.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_sram.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_ll_fmc.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_i2c.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_i2c_ex.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_pwr.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_pwr_ex.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_rtc.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_rtc_ex.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_sai.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_spi.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_tim.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_tim_ex.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_pcd.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_ll_usb.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_pcd_ex.h:
basesw/ovi40/Drivers/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal_hcd.h:
basesw/ovi40/Inc/stm32f7xx_it.h:
hardware/uhsdr_board.h:
hardware/uhsdr_board_config.h:
hardware/board_configs/UHSDR_UI_mchf_config.h:
hardware/uhsdr_types.h:
basesw/ovi40/Drivers/CMSIS/Include/arm_math.h:
basesw/ovi40/Drivers/CMSIS/Include/core_cm7.h:
hardware/uhsdr_mcu.h:
drivers/audio/audio_filter.h:
hardware/uhsdr_types.h:
drivers/ui/oscillator/osc_interface.h:
drivers/ui/lcd/ui_lcd_layouts.h:
drivers/ui/lcd/ui_lcd_hy28.h:
drivers/ui/ui_vkeybrd.h:
drivers/audio/audio_driver.h:
hardware/uhsdr_board_config.h:
drivers/audio/softdds/softdds.h:
drivers/audio/softdds/dds_table.h:
drivers/audio/audio_filter.h:
