drivers/audio/audio_driver.o: drivers/audio/audio_driver.c \
 hardware/uhsdr_board.h hardware/uhsdr_board_config.h \
 hardware/board_configs/UHSDR_UI_mchf_config.h \
 basesw/mcHF/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h \
 basesw/mcHF/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f407xx.h \
 basesw/mcHF/Drivers/CMSIS/Include/core_cm4.h \
 basesw/mcHF/Drivers/CMSIS/Include/core_cmInstr.h \
 basesw/mcHF/Drivers/CMSIS/Include/cmsis_gcc.h \
 basesw/mcHF/Drivers/CMSIS/Include/core_cmFunc.h \
 basesw/mcHF/Drivers/CMSIS/Include/core_cmSimd.h \
 basesw/mcHF/Drivers/CMSIS/Device/ST/STM32F4xx/Include/system_stm32f4xx.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal.h \
 basesw/mcHF/Inc/stm32f4xx_hal_conf.h basesw/mcHF/Inc/main.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_def.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_gpio.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_gpio_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dma.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dma_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_cortex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_adc.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_adc_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dac.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dac_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash_ramfunc.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_sram.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_fsmc.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2c.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2c_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2s.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2s_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_iwdg.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pwr.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pwr_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rtc.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rtc_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_spi.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_tim.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_tim_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pcd.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_usb.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pcd_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_hcd.h \
 hardware/board_configs/UHSDR_RF_mchf_config.h hardware/uhsdr_types.h \
 basesw/mcHF/Drivers/CMSIS/Include/arm_math.h \
 basesw/mcHF/Drivers/CMSIS/Include/core_cm4.h hardware/uhsdr_mcu.h \
 drivers/audio/audio_filter.h hardware/uhsdr_types.h \
 drivers/ui/oscillator/osc_interface.h drivers/ui/lcd/ui_lcd_layouts.h \
 drivers/ui/lcd/ui_lcd_hy28.h drivers/ui/ui_vkeybrd.h \
 drivers/audio/audio_driver.h hardware/uhsdr_board_config.h \
 drivers/audio/softdds/softdds.h drivers/audio/softdds/dds_table.h \
 drivers/audio/audio_filter.h drivers/audio/audio_driver_filters.h \
 drivers/audio/audio_driver.h drivers/ui/ui_driver.h \
 drivers/ui/ui_spectrum_ctrl.h drivers/ui/ui_driver.h misc/profiling.h \
 drivers/audio/codec/codec.h drivers/ui/ui_configuration.h \
 drivers/audio/cw/cw_gen.h drivers/audio/audio_driver.h \
 drivers/audio/audio_driver_ctx.h drivers/audio/audio_nr.h \
 drivers/audio/freedv_uhsdr.h drivers/freedv/comp.h drivers/audio/rb.h \
 drivers/audio/audio_agc.h drivers/audio/audio_management.h \
 drivers/ui/radio_management.h drivers/usb/app/usbd_audio_if.h \
 drivers/usb/device/class/AUDIO/Inc/usbd_audio_cdc_comp.h \
 basesw/mcHF/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_ioreq.h \
 basesw/mcHF/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_def.h \
 basesw/mcHF/Inc/usbd_conf.h \
 basesw/mcHF/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_core.h \
 basesw/mcHF/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_ioreq.h \
 basesw/mcHF/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_ctlreq.h \
 drivers/usb/app/usbd_desc.h \
 basesw/mcHF/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_def.h \
 drivers/ui/lcd/ui_spectrum.h \
 basesw/mcHF/Drivers/CMSIS/Include/arm_const_structs.h \
 basesw/mcHF/Drivers/CMSIS/Include/arm_math.h \
 basesw/mcHF/Drivers/CMSIS/Include/arm_common_tables.h \
 drivers/ui/lcd/ui_lcd_layouts.h drivers/audio/filters/filters.h \
 hal/include/hal_i2s.h hal/include/hal_common.h drivers/audio/rtty.h \
 drivers/audio/psk.h drivers/audio/cw/cw_decoder.h \
 drivers/audio/freq_shift.h drivers/audio/fm_subaudible_tone_table.h \
 misc/uhsdr_math.h drivers/audio/audio_driver_filters.h \
 drivers/audio/tx_processor.h
hardware/uhsdr_board.h:
hardware/uhsdr_board_config.h:
hardware/board_configs/UHSDR_UI_mchf_config.h:
basesw/mcHF/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h:
basesw/mcHF/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f407xx.h:
basesw/mcHF/Drivers/CMSIS/Include/core_cm4.h:
basesw/mcHF/Drivers/CMSIS/Include/core_cmInstr.h:
basesw/mcHF/Drivers/CMSIS/Include/cmsis_gcc.h:
basesw/mcHF/Drivers/CMSIS/Include/core_cmFunc.h:
basesw/mcHF/Drivers/CMSIS/Include/core_cmSimd.h:
basesw/mcHF/Drivers/CMSIS/Device/ST/STM32F4xx/Include/system_stm32f4xx.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal.h:
basesw/mcHF/Inc/stm32f4xx_hal_conf.h:
basesw/mcHF/Inc/main.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_def.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_gpio.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_gpio_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dma.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dma_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_cortex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_adc.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_adc_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dac.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dac_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash_ramfunc.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_sram.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_fsmc.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2c.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2c_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2s.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2s_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_iwdg.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pwr.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pwr_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rtc.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rtc_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_spi.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_tim.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_tim_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pcd.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_usb.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pcd_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_hcd.h:
hardware/board_configs/UHSDR_RF_mchf_config.h:
hardware/uhsdr_types.h:
basesw/mcHF/Drivers/CMSIS/Include/arm_math.h:
basesw/mcHF/Drivers/CMSIS/Include/core_cm4.h:
hardware/uhsdr_mcu.h:
drivers/audio/audio_filter.h:
hardware/uhsdr_types.h:
drivers/ui/oscillator/osc_interface.h:
drivers/ui/lcd/ui_lcd_layouts.h:
drivers/ui/lcd/ui_lcd_hy28.h:
drivers/ui/ui_vkeybrd.h:
drivers/audio/audio_driver.h:
hardware/uhsdr_board_config.h:
drivers/audio/softdds/softdds.h:
drivers/audio/softdds/dds_table.h:
drivers/audio/audio_filter.h:
drivers/audio/audio_driver_filters.h:
drivers/audio/audio_driver.h:
drivers/ui/ui_driver.h:
drivers/ui/ui_spectrum_ctrl.h:
drivers/ui/ui_driver.h:
misc/profiling.h:
drivers/audio/codec/codec.h:
drivers/ui/ui_configuration.h:
drivers/audio/cw/cw_gen.h:
drivers/audio/audio_driver.h:
drivers/audio/audio_driver_ctx.h:
drivers/audio/audio_nr.h:
drivers/audio/freedv_uhsdr.h:
drivers/freedv/comp.h:
drivers/audio/rb.h:
drivers/audio/audio_agc.h:
drivers/audio/audio_management.h:
drivers/ui/radio_management.h:
drivers/usb/app/usbd_audio_if.h:
drivers/usb/device/class/AUDIO/Inc/usbd_audio_cdc_comp.h:
basesw/mcHF/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_ioreq.h:
basesw/mcHF/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_def.h:
basesw/mcHF/Inc/usbd_conf.h:
basesw/mcHF/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_core.h:
basesw/mcHF/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_ioreq.h:
basesw/mcHF/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_ctlreq.h:
drivers/usb/app/usbd_desc.h:
basesw/mcHF/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_def.h:
drivers/ui/lcd/ui_spectrum.h:
basesw/mcHF/Drivers/CMSIS/Include/arm_const_structs.h:
basesw/mcHF/Drivers/CMSIS/Include/arm_math.h:
basesw/mcHF/Drivers/CMSIS/Include/arm_common_tables.h:
drivers/ui/lcd/ui_lcd_layouts.h:
drivers/audio/filters/filters.h:
hal/include/hal_i2s.h:
hal/include/hal_common.h:
drivers/audio/rtty.h:
drivers/audio/psk.h:
drivers/audio/cw/cw_decoder.h:
drivers/audio/freq_shift.h:
drivers/audio/fm_subaudible_tone_table.h:
misc/uhsdr_math.h:
drivers/audio/audio_driver_filters.h:
drivers/audio/tx_processor.h:
