drivers/audio/audio_rx.o: drivers/audio/audio_rx.c \
 drivers/audio/audio_rx.h drivers/audio/audio_driver.h \
 hardware/uhsdr_board_config.h \
 hardware/board_configs/UHSDR_UI_mchf_config.h \
 basesw/mcHF/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h \
 basesw/mcHF/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f407xx.h \
 basesw/mcHF/Drivers/CMSIS/Include/core_cm4.h \
 basesw/mcHF/Drivers/CMSIS/Include/core_cmInstr.h \
 basesw/mcHF/Drivers/CMSIS/Include/cmsis_gcc.h \
 basesw/mcHF/Drivers/CMSIS/Include/core_cmFunc.h \
 basesw/mcHF/Drivers/CMSIS/Include/core_cmSimd.h \
 basesw/mcHF/Drivers/CMSIS/Device/ST/STM32F4xx/Include/system_stm32f4xx.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal.h \
 basesw/mcHF/Inc/stm32f4xx_hal_conf.h basesw/mcHF/Inc/main.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_def.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_gpio.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_gpio_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dma.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dma_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_cortex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_adc.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_adc_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dac.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dac_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash_ramfunc.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_sram.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_fsmc.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2c.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2c_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2s.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2s_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_iwdg.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pwr.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pwr_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rtc.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rtc_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_spi.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_tim.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_tim_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pcd.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_usb.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pcd_ex.h \
 basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_hcd.h \
 hardware/board_configs/UHSDR_RF_mchf_config.h hardware/uhsdr_types.h \
 basesw/mcHF/Drivers/CMSIS/Include/arm_math.h \
 basesw/mcHF/Drivers/CMSIS/Include/core_cm4.h hardware/uhsdr_types.h \
 drivers/audio/softdds/softdds.h drivers/audio/softdds/dds_table.h \
 drivers/audio/audio_filter.h drivers/audio/audio_driver_filters.h
drivers/audio/audio_rx.h:
drivers/audio/audio_driver.h:
hardware/uhsdr_board_config.h:
hardware/board_configs/UHSDR_UI_mchf_config.h:
basesw/mcHF/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h:
basesw/mcHF/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f407xx.h:
basesw/mcHF/Drivers/CMSIS/Include/core_cm4.h:
basesw/mcHF/Drivers/CMSIS/Include/core_cmInstr.h:
basesw/mcHF/Drivers/CMSIS/Include/cmsis_gcc.h:
basesw/mcHF/Drivers/CMSIS/Include/core_cmFunc.h:
basesw/mcHF/Drivers/CMSIS/Include/core_cmSimd.h:
basesw/mcHF/Drivers/CMSIS/Device/ST/STM32F4xx/Include/system_stm32f4xx.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal.h:
basesw/mcHF/Inc/stm32f4xx_hal_conf.h:
basesw/mcHF/Inc/main.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_def.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_gpio.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_gpio_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dma.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dma_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_cortex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_adc.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_adc_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dac.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_dac_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_flash_ramfunc.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_sram.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_fsmc.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2c.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2c_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2s.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2s_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_iwdg.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pwr.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pwr_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rtc.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rtc_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_spi.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_tim.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_tim_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pcd.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_usb.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_pcd_ex.h:
basesw/mcHF/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_hcd.h:
hardware/board_configs/UHSDR_RF_mchf_config.h:
hardware/uhsdr_types.h:
basesw/mcHF/Drivers/CMSIS/Include/arm_math.h:
basesw/mcHF/Drivers/CMSIS/Include/core_cm4.h:
hardware/uhsdr_types.h:
drivers/audio/softdds/softdds.h:
drivers/audio/softdds/dds_table.h:
drivers/audio/audio_filter.h:
drivers/audio/audio_driver_filters.h:
